# Generated by Django 5.1.5 on 2026-09-02 15:41

import consulti.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoreAnno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contatore annuale',
                'verbose_name_plural': 'Contatori annuali',
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ECG_PDF', 'Tracciato ECG (PDF)'), ('ECG_IMMAGINE', 'Tracciato ECG (immagine)'), ('HOLTER_REFERTO', "Referto Holter dell'apparecchio"), ('HOLTER_FILE', 'File grezzo Holter'), ('ECO_REFERTO_PDF', 'Referto ecografo (PDF)'), ('ECO_STATICA', 'Immagine eco statica'), ('ECO_CLIP', 'Clip eco'), ('ALTRO', 'Altro')], db_index=True, max_length=20)),
                ('file', models.FileField(max_length=300, upload_to=consulti.models.percorso_allegato)),
                ('nome_originale', models.CharField(blank=True, max_length=255)),
                ('dimensione', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('stato', models.CharField(choices=[('CARICATO', 'Caricato'), ('TRANSCODIFICATO', 'Transcodificato'), ('SCARTATO', 'Scartato')], default='CARICATO', max_length=20)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
                'ordering': ['caricato_il'],
            },
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(editable=False, max_length=15, unique=True)),
                ('tipo_esame', models.CharField(choices=[('ECG', 'Elettrocardiogramma'), ('HOLTER', 'Holter'), ('ECO', 'Ecocardiografia')], db_index=True, max_length=10)),
                ('urgenza', models.BooleanField(default=False)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata'), ('PRESA_IN_CARICO', 'Presa in carico'), ('REFERTATA', 'Refertata'), ('NON_REFERTABILE', 'Non refertabile'), ('DECLINATA', 'Declinata'), ('ANNULLATA', 'Annullata')], db_index=True, default='BOZZA', max_length=20)),
                ('quesito', models.TextField(blank=True, help_text='Cosa si chiede al collega.')),
                ('anamnesi', models.TextField(blank=True)),
                ('terapia', models.TextField(blank=True, help_text='Terapia in corso.')),
                ('motivo_esame', models.CharField(blank=True, max_length=200)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('inviata_il', models.DateTimeField(blank=True, null=True)),
                ('presa_in_carico_il', models.DateTimeField(blank=True, null=True)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('motivo_rifiuto', models.TextField(blank=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Vuota se chiede un libero professionista.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='richieste', to='accounts.clinica')),
                ('refertatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='richieste', to='accounts.refertatore')),
                ('richiedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='richieste', to='accounts.richiedente')),
            ],
            options={
                'verbose_name': 'Richiesta di consulto',
                'verbose_name_plural': 'Richieste di consulto',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('specie', models.CharField(choices=[('CANE', 'Cane'), ('GATTO', 'Gatto'), ('ALTRO', 'Altro')], default='CANE', max_length=10)),
                ('specie_altro', models.CharField(blank=True, max_length=50)),
                ('razza', models.CharField(blank=True, max_length=100)),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('MC', 'Maschio castrato'), ('F', 'Femmina'), ('FS', 'Femmina sterilizzata'), ('ND', 'Non noto')], default='ND', max_length=2)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('eta_testo', models.CharField(blank=True, help_text="Es. «8 anni», se la data non e' nota.", max_length=30)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cognome_proprietario', models.CharField(blank=True, max_length=100)),
                ('richiesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paziente', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Paziente',
                'verbose_name_plural': 'Pazienti',
            },
        ),
        migrations.CreateModel(
            name='EventoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(db_index=True, max_length=40)),
                ('dettaglio', models.JSONField(blank=True, default=dict)),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Evento di audit',
                'verbose_name_plural': 'Eventi di audit',
                'ordering': ['quando'],
            },
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('allegato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulti.allegato')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Commento',
                'verbose_name_plural': 'Commenti',
                'ordering': ['quando'],
            },
        ),
        migrations.AddField(
            model_name='allegato',
            name='richiesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='consulti.richiesta'),
        ),
    ]
