# Generated by Django 5.1.5 on 2026-09-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paziente',
            name='specie_altro',
        ),
        migrations.AlterField(
            model_name='paziente',
            name='specie',
            field=models.CharField(choices=[('CANE', 'Cane'), ('GATTO', 'Gatto')], default='CANE', max_length=10),
        ),
    ]
