# Generated by Django 5.1.5 on 2026-09-11 21:44

import consulti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulti', '0002_specie_solo_cane_gatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='anteprima',
            field=models.ImageField(blank=True, max_length=300, upload_to=consulti.models.percorso_anteprima),
        ),
    ]
