# Generated by Django 5.1.5 on 2026-09-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_competenza_accetta_urgenze'),
        ('consulti', '0003_allegato_anteprima'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='con_riserva',
            field=models.BooleanField(default=False, help_text="Presa in carico con riserva: l'esperto ha chiesto integrazioni."),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='inviata_incompleta',
            field=models.BooleanField(default=False, help_text="Inviata senza tutte le proiezioni consigliate, con presa d'atto del richiedente."),
        ),
        migrations.CreateModel(
            name='Integrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(help_text='Cosa manca o cosa va rifatto. Lo legge chi ha chiesto il consulto.')),
                ('chiesta_il', models.DateTimeField(auto_now_add=True)),
                ('evasa_il', models.DateTimeField(blank=True, null=True)),
                ('chiesta_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrazioni_chieste', to='accounts.refertatore')),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrazioni', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Richiesta di integrazione',
                'verbose_name_plural': 'Richieste di integrazione',
                'ordering': ['-chiesta_il'],
            },
        ),
    ]
