# Generated by Django 5.1.5 on 2026-09-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True)),
                ('conclusioni', models.TextField(blank=True)),
                ('raccomandazioni', models.TextField(blank=True)),
                ('classificazione', models.JSONField(blank=True, default=dict, help_text='Per esame. ECG: {"rischio_anestesia": "basso"} ecc.')),
                ('firmato_il', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, max_length=300, null=True, upload_to='referti/%Y/')),
                ('versione', models.PositiveIntegerField(default=1)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('firmato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referti_firmati', to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referto', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Referto',
                'verbose_name_plural': 'Referti',
                'ordering': ['-creato_il'],
            },
        ),
    ]
