# Generated by Django 5.1.5 on 2026-09-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True)),
                ('conclusioni', models.TextField(blank=True)),
                ('raccomandazioni', models.TextField(blank=True)),
                ('classificazione', models.JSONField(blank=True, default=dict, help_text='Per esame. ECG: {"rischio_anestesia": "BASSO"} ecc.')),
                ('motivo_rettifica', models.TextField(blank=True, help_text='Bozza del motivo della prossima rettifica; passa alla versione quando la si emette.')),
                ('firmato_il', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, help_text="PDF dell'ultima versione firmata (lo stesso file della versione).", max_length=300, null=True, upload_to='referti/%Y/')),
                ('versione', models.PositiveIntegerField(default=1, help_text="Numero dell'ultima versione firmata.")),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('firmato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referti_firmati', to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referto', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Referto',
                'verbose_name_plural': 'Referti',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='VersioneReferto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descrizione', models.TextField(blank=True)),
                ('conclusioni', models.TextField()),
                ('raccomandazioni', models.TextField(blank=True)),
                ('classificazione', models.JSONField(blank=True, default=dict)),
                ('firmato_il', models.DateTimeField()),
                ('motivo_rettifica', models.TextField(blank=True, help_text='Vuoto per la versione 1.')),
                ('pdf', models.FileField(blank=True, max_length=300, null=True, upload_to='referti/%Y/')),
                ('firmato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versioni_firmate', to=settings.AUTH_USER_MODEL)),
                ('referto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versioni', to='referti.referto')),
            ],
            options={
                'verbose_name': 'Versione del referto',
                'verbose_name_plural': 'Versioni del referto',
                'ordering': ['referto', '-numero'],
                'constraints': [models.UniqueConstraint(fields=('referto', 'numero'), name='versione_unica_per_referto')],
            },
        ),
    ]
