# Generated by Django 5.1.5 on 2026-09-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('oggetto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CASO_ARRIVATO', 'Nuovo caso per il refertatore'), ('REFERTO_PRONTO', 'Referto pronto per il richiedente'), ('REFERTO_RETTIFICATO', 'Referto rettificato per il richiedente'), ('CASO_DECLINATO', 'Caso declinato: il richiedente deve sceglierne un altro'), ('NON_REFERTABILE', 'Caso non refertabile per il richiedente'), ('SOLLECITO', "Sollecito al refertatore a meta' tempo"), ('RILASCIO', "Presa in carico rilasciata per inattivita'"), ('ALTRO', 'Altro')], default='ALTRO', max_length=20)),
                ('inviata_il', models.DateTimeField(auto_now_add=True)),
                ('esito', models.CharField(choices=[('OK', 'Inviata'), ('ERRORE', 'Errore')], max_length=10)),
                ('errore', models.TextField(blank=True)),
                ('allegati', models.CharField(blank=True, help_text='Nomi dei file allegati, separati da virgola.', max_length=300)),
                ('richiesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invii_email', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Invio email',
                'verbose_name_plural': 'Invii email',
                'ordering': ['-inviata_il'],
            },
        ),
    ]
