# Generated by Django 5.1.5 on 2026-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiche', '0002_alter_invioemail_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invioemail',
            name='tipo',
            field=models.CharField(choices=[('CASO_ARRIVATO', 'Nuovo caso per il refertatore'), ('REFERTO_PRONTO', 'Referto pronto per il richiedente'), ('REFERTO_RETTIFICATO', 'Referto rettificato per il richiedente'), ('CASO_DECLINATO', 'Caso declinato: il richiedente deve sceglierne un altro'), ('NON_REFERTABILE', 'Caso non refertabile per il richiedente'), ('SOLLECITO', "Sollecito al refertatore a meta' tempo"), ('RILASCIO', "Presa in carico rilasciata per inattivita'"), ('CASO_TOLTO', 'Caso affidato a un altro esperto (al precedente)'), ('CASO_SPOSTATO', 'Caso affidato a un altro esperto (al richiedente)'), ('CASO_ANNULLATO', 'Caso annullato dalla gestione'), ('ISCRIZIONE', 'Nuova iscrizione, da approvare (al gestore)'), ('APPROVAZIONE', 'Profilo approvato (al richiedente)'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20),
        ),
    ]
