# Generated by Django 5.1.5 on 2026-09-02 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=200)),
                ('cap', models.CharField(blank=True, max_length=5)),
                ('comune', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('approvata', models.BooleanField(db_index=True, default=False, help_text="Finche' non e' approvata, le sue richieste non partono.")),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinica',
                'verbose_name_plural': 'Cliniche',
                'ordering': ['denominazione'],
            },
        ),
        migrations.CreateModel(
            name='DatiFatturazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intestatario', models.CharField(max_length=200)),
                ('partita_iva', models.CharField(blank=True, max_length=11)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('indirizzo_sede', models.CharField(max_length=200)),
                ('cap', models.CharField(max_length=5)),
                ('comune', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=2)),
                ('nazione', models.CharField(default='IT', max_length=2)),
                ('codice_sdi', models.CharField(default='0000000', max_length=7, verbose_name='Codice destinatario SDI')),
                ('pec_fatturazione', models.EmailField(blank=True, max_length=254)),
                ('regime_iva', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('FORFETTARIO', 'Forfettario (art. 1 c. 54-89 L. 190/2014)'), ('ESENTE', 'Esente / non imponibile')], default='ORDINARIO', max_length=20)),
                ('split_payment', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('predefinita', models.BooleanField(default=False, help_text='Usata per le nuove richieste. Una sola per clinica.')),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dati_fatturazione', to='accounts.clinica')),
            ],
            options={
                'verbose_name': 'Dati di fatturazione',
                'verbose_name_plural': 'Dati di fatturazione',
            },
        ),
        migrations.CreateModel(
            name='Refertatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, help_text='Es. Dott., Dott.ssa, Prof.', max_length=50)),
                ('specializzazione', models.CharField(blank=True, max_length=200)),
                ('numero_iscrizione', models.CharField(blank=True, max_length=30)),
                ('ordine_provinciale', models.CharField(blank=True, max_length=100)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firme/')),
                ('attivo', models.BooleanField(db_index=True, default=True)),
                ('assente_dal', models.DateField(blank=True, null=True)),
                ('assente_al', models.DateField(blank=True, null=True)),
                ('messaggio', models.CharField(blank=True, help_text="Compare accanto al nome nell'elenco. Es. tempi di risposta.", max_length=200)),
                ('soggetto_emittente', models.CharField(choices=[('SOCIETA', "La societa' (VetWay)"), ('REFERTATORE', 'Il refertatore in proprio')], default='SOCIETA', help_text='Chi emette la fattura per le sue prestazioni.', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('dati_fatturazione', models.ForeignKey(blank=True, help_text='Necessari solo se emette in proprio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refertatori', to='accounts.datifatturazione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refertatore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refertatore',
                'verbose_name_plural': 'Refertatori',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Richiedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLINICA', 'Clinica / struttura veterinaria'), ('LIBERO_PROFESSIONISTA', 'Libero professionista')], db_index=True, default='CLINICA', max_length=25)),
                ('approvato', models.BooleanField(db_index=True, default=False, help_text="Solo per il libero professionista: finche' non e' approvato, le sue richieste non partono.")),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('numero_iscrizione', models.CharField(blank=True, max_length=30)),
                ('ordine_provinciale', models.CharField(blank=True, max_length=100)),
                ('ruolo', models.CharField(choices=[('VETERINARIO', 'Medico veterinario'), ('TECNICO', 'Tecnico veterinario')], default='VETERINARIO', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Obbligatoria per il tipo CLINICA.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='richiedenti', to='accounts.clinica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='richiedente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiedente',
                'verbose_name_plural': 'Richiedenti',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='datifatturazione',
            name='richiedente',
            field=models.ForeignKey(blank=True, help_text='Solo per un libero professionista che si fa fatturare a proprio nome.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dati_fatturazione', to='accounts.richiedente'),
        ),
        migrations.CreateModel(
            name='Consenso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRIVACY', 'Informativa privacy'), ('TERMINI', 'Termini del servizio')], max_length=10)),
                ('versione', models.CharField(max_length=20)),
                ('accettato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consenso',
                'verbose_name_plural': 'Consensi',
                'ordering': ['-accettato_il'],
                'unique_together': {('user', 'tipo', 'versione')},
            },
        ),
        migrations.CreateModel(
            name='CompetenzaRefertatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_esame', models.CharField(choices=[('ECG', 'Elettrocardiogramma'), ('HOLTER', 'Holter'), ('ECO', 'Ecocardiografia')], max_length=10)),
                ('referente', models.BooleanField(default=False)),
                ('prezzo_personalizzato', models.DecimalField(blank=True, decimal_places=2, help_text='Imponibile. Vuoto = listino.', max_digits=8, null=True)),
                ('tempo_risposta_ore', models.PositiveIntegerField(blank=True, null=True)),
                ('refertatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competenze', to='accounts.refertatore')),
            ],
            options={
                'verbose_name': 'Competenza refertatore',
                'verbose_name_plural': 'Competenze refertatori',
                'ordering': ['refertatore', 'tipo_esame'],
                'unique_together': {('refertatore', 'tipo_esame')},
            },
        ),
        migrations.AddConstraint(
            model_name='datifatturazione',
            constraint=models.CheckConstraint(condition=models.Q(('clinica__isnull', True), ('richiedente__isnull', True), _connector='OR'), name='dati_fatturazione_un_solo_soggetto'),
        ),
        migrations.AddConstraint(
            model_name='datifatturazione',
            constraint=models.UniqueConstraint(condition=models.Q(('predefinita', True)), fields=('clinica',), name='una_sola_predefinita_per_clinica'),
        ),
        migrations.AddConstraint(
            model_name='datifatturazione',
            constraint=models.UniqueConstraint(condition=models.Q(('predefinita', True)), fields=('richiedente',), name='una_sola_predefinita_per_richiedente'),
        ),
    ]
