# Generated by Django 5.1.5 on 2026-09-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refertatore',
            name='foto',
            field=models.ImageField(blank=True, help_text="Compare ai colleghi nella scelta dell'esperto. Si riduce da sola a 480 px.", null=True, upload_to='foto_refertatori/'),
        ),
    ]
