# Generated by Django 5.1.5 on 2026-09-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_refertatore_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenzarefertatore',
            name='accetta_urgenze',
            field=models.BooleanField(default=False, help_text="Accetta i casi urgenti di questo tipo: risposta entro 4 ore dall'invio."),
        ),
    ]
