# Generated by Django 5.1.5 on 2026-09-02 15:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('descrizione', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('URGENZA', 'Urgenza'), ('ALTRO', 'Altro')], default='ALTRO', max_length=10)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentuale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valido_dal', models.DateField()),
                ('valido_al', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplemento',
                'verbose_name_plural': 'Supplementi',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='VoceListino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_esame', models.CharField(choices=[('ECG', 'Elettrocardiogramma'), ('HOLTER', 'Holter'), ('ECO', 'Ecocardiografia')], db_index=True, max_length=10)),
                ('descrizione', models.CharField(max_length=200)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Imponibile')),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5)),
                ('valido_dal', models.DateField()),
                ('valido_al', models.DateField(blank=True, help_text='Vuoto = ancora in vigore.', null=True)),
            ],
            options={
                'verbose_name': 'Voce di listino',
                'verbose_name_plural': 'Voci di listino',
                'ordering': ['tipo_esame', '-valido_dal'],
            },
        ),
    ]
