# Generated by Django 5.1.5 on 2026-09-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProiezioneCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descrizione', models.TextField(blank=True)),
                ('istruzioni_misura', models.TextField(blank=True, help_text='Cosa misurare e come, in breve.')),
                ('immagine_riferimento', models.ImageField(blank=True, null=True, upload_to='eco_riferimento/')),
                ('tipo_media', models.CharField(choices=[('CLIP', 'Clip'), ('STATICA', 'Immagine statica'), ('ENTRAMBI', 'Clip e statica')], default='CLIP', max_length=10)),
                ('obbligatoria', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proiezione (catalogo)',
                'verbose_name_plural': 'Proiezioni (catalogo)',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='ProiezioneCaricata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('allegato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proiezioni', to='consulti.allegato')),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proiezioni', to='consulti.richiesta')),
                ('proiezione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.proiezionecatalogo')),
            ],
            options={
                'verbose_name': 'Proiezione caricata',
                'verbose_name_plural': 'Proiezioni caricate',
                'ordering': ['proiezione__ordine'],
            },
        ),
    ]
