# Generated by Django 5.1.5 on 2026-09-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proiezionecatalogo',
            name='immagine_riferimento',
        ),
        migrations.RemoveField(
            model_name='proiezionecatalogo',
            name='istruzioni_misura',
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='deve_essere_visibile',
            field=models.TextField(blank=True, help_text="Cosa deve vedersi nel filmato o nell'immagine: la legge chi carica."),
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='finestra',
            field=models.CharField(choices=[('PARASTERNALE_DESTRA', 'Parasternale destra'), ('SOTTOXIFOIDEA', 'Sottoxifoidea'), ('PARASTERNALE_SINISTRA', 'Parasternale sinistra, apicale e craniale'), ('ALTRO', 'Filmati liberi')], default='ALTRO', help_text='Finestra acustica: raggruppa le righe nel passo «Carica gli esami».', max_length=25),
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='istruzioni',
            field=models.TextField(blank=True, help_text='Come si acquisisce: la legge chi carica.'),
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='libera',
            field=models.BooleanField(default=False, help_text='Filmato libero: facoltativo, con una nota di chi carica («cosa mostra / cosa chiedi»).'),
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='nota_riferimento',
            field=models.TextField(blank=True, help_text="Appunto su immagini di riferimento o contenuti: compare solo qui nell'admin."),
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='scheda_guida',
            field=models.CharField(blank=True, help_text='Scheda della guida da cui viene la voce (es. DX-1).', max_length=20),
        ),
        migrations.AddField(
            model_name='proiezionecatalogo',
            name='serve_per',
            field=models.TextField(blank=True, help_text='A cosa serve (anche soglie cliniche): nel passo di caricamento sta in un richiudibile.'),
        ),
        migrations.AlterField(
            model_name='proiezionecatalogo',
            name='tipo_media',
            field=models.CharField(choices=[('CLIP', 'Clip'), ('STATICA', 'Immagine statica'), ('ENTRAMBI', 'Clip o statica')], default='CLIP', max_length=10),
        ),
        migrations.CreateModel(
            name='ImmagineRiferimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='eco_riferimento/')),
                ('didascalia', models.CharField(blank=True, max_length=120)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('proiezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='eco.proiezionecatalogo')),
            ],
            options={
                'verbose_name': 'Immagine di riferimento',
                'verbose_name_plural': 'Immagini di riferimento',
                'ordering': ['proiezione', 'ordine', 'pk'],
            },
        ),
    ]
