# Generated by Django 5.1.5 on 2026-09-11 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulti', '0002_allegato_anteprima'),
        ('eco', '0002_catalogo_definitivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Smistamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('IN_CORSO', 'In corso'), ('FATTO', 'Fatto'), ('ERRORE', 'Non riuscito')], default='IN_CORSO', max_length=10)),
                ('avviato_il', models.DateTimeField(auto_now_add=True)),
                ('finito_il', models.DateTimeField(blank=True, null=True)),
                ('n_file', models.PositiveIntegerField(default=0)),
                ('modello', models.CharField(blank=True, max_length=60)),
                ('lettura_ai', models.BooleanField(default=False, help_text='La lettura AI ha risposto per almeno un file.')),
                ('messaggio', models.TextField(blank=True)),
                ('telemetria', models.JSONField(blank=True, default=dict)),
                ('avviato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smistamenti', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Smistamento automatico',
                'verbose_name_plural': 'Smistamenti automatici',
                'ordering': ['-avviato_il', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PropostaSmistamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referto', models.BooleanField(default=False, help_text="Proposto come referto dell'ecografo (PDF).")),
                ('nota', models.CharField(blank=True, help_text='Per i filmati liberi: cosa mostra / cosa chiedi.', max_length=200)),
                ('fonte', models.CharField(blank=True, choices=[('', 'Da smistare'), ('FORMATO', 'Dal formato del file'), ('AI', 'Lettura automatica'), ('ORDINE', "Dall'ordine di acquisizione"), ('MANUALE', 'Scelta di chi carica'), ('RIGA', 'Caricato nella riga')], default='', max_length=10)),
                ('confidenza', models.FloatField(blank=True, null=True)),
                ('sicura', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('tracciato', models.CharField(blank=True, help_text='Tipo di tracciato letto dalla AI.', max_length=20)),
                ('colore', models.CharField(blank=True, help_text='color / bmode / incerto, dai pixel.', max_length=10)),
                ('percorso_originale', models.CharField(blank=True, help_text='Percorso nella cartella caricata (ordine di acquisizione).', max_length=500)),
                ('modificato_il', models.BigIntegerField(blank=True, help_text='Data di modifica del file (ms), dal browser.', null=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('allegato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_smistamento', to='consulti.allegato')),
                ('proiezione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eco.proiezionecatalogo')),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_smistamento', to='consulti.richiesta')),
                ('seconda_scelta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eco.proiezionecatalogo')),
            ],
            options={
                'verbose_name': 'Proposta di smistamento',
                'verbose_name_plural': 'Proposte di smistamento',
                'constraints': [models.UniqueConstraint(condition=models.Q(('proiezione__isnull', False)), fields=('richiesta', 'proiezione'), name='una_proposta_per_riga')],
            },
        ),
    ]
