# Generated by Django 5.1.5 on 2026-09-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulti', '0003_allegato_anteprima'),
        ('eco', '0003_smistamento_propostasmistamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsitoSmistamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_richiesta', models.CharField(blank=True, help_text='Identificativo interno del caso: resta se la richiesta sparisce.', max_length=15)),
                ('allegato_interno', models.BigIntegerField(help_text="id interno dell'allegato.")),
                ('modello', models.CharField(blank=True, max_length=60)),
                ('proposta', models.CharField(blank=True, help_text='Codice della riga proposta; vuoto = nessuna.', max_length=30)),
                ('proposta_referto', models.BooleanField(default=False)),
                ('fonte', models.CharField(blank=True, help_text='FORMATO / AI / ORDINE (FonteProposta).', max_length=10)),
                ('confidenza', models.FloatField(blank=True, null=True)),
                ('sicura', models.BooleanField(default=False)),
                ('tracciato', models.CharField(blank=True, help_text='Tipo di tracciato letto dalla AI.', max_length=20)),
                ('seconda_scelta', models.CharField(blank=True, max_length=30)),
                ('proposto_il', models.DateTimeField(auto_now_add=True)),
                ('confermato_il', models.DateTimeField(blank=True, null=True)),
                ('finale', models.CharField(blank=True, help_text='Codice della riga confermata; vuoto = nessuna.', max_length=30)),
                ('finale_referto', models.BooleanField(default=False)),
                ('corretto', models.BooleanField(default=False, help_text="L'umano ha spostato il file altrove.")),
                ('richiesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esiti_smistamento', to='consulti.richiesta')),
                ('smistamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esiti', to='eco.smistamento')),
            ],
            options={
                'verbose_name': 'Esito dello smistamento',
                'verbose_name_plural': 'Esiti dello smistamento',
                'ordering': ['-proposto_il', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('richiesta', 'allegato_interno'), name='un_esito_per_file')],
            },
        ),
    ]
