# Generated by Django 5.1.5 on 2026-09-02 15:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('consulti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_esame', models.CharField(choices=[('ECG', 'Elettrocardiogramma'), ('HOLTER', 'Holter'), ('ECO', 'Ecocardiografia')], max_length=10)),
                ('data', models.DateField(db_index=True)),
                ('soggetto_emittente', models.CharField(choices=[('SOCIETA', "La societa' (VetWay)"), ('REFERTATORE', 'Il refertatore in proprio')], max_length=20)),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplementi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('origine_prezzo', models.CharField(max_length=20)),
                ('registrata_il', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Vuota se la fattura va al richiedente (libero professionista).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni', to='accounts.clinica')),
                ('refertatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni', to='accounts.refertatore')),
                ('richiedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni', to='accounts.richiedente')),
                ('richiesta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestazione', to='consulti.richiesta')),
            ],
            options={
                'verbose_name': 'Prestazione',
                'verbose_name_plural': 'Prestazioni',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StatoFatturazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('DA_FATTURARE', 'Da fatturare'), ('FATTURATA', 'Fatturata'), ('PAGATA', 'Pagata'), ('STORNATA', 'Stornata')], db_index=True, default='DA_FATTURARE', max_length=20)),
                ('numero_fattura', models.CharField(blank=True, max_length=50)),
                ('data_fattura', models.DateField(blank=True, null=True)),
                ('riferimento_esterno', models.CharField(blank=True, help_text='Id nel gestionale.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('prestazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatturazione', to='registro.prestazione')),
            ],
            options={
                'verbose_name': 'Stato fatturazione',
                'verbose_name_plural': 'Stati fatturazione',
            },
        ),
    ]
